# Generated by Django 2.2.6 on 2019-10-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='views',
            new_name='user_likes',
        ),
        migrations.AddField(
            model_name='product',
            name='user_views',
            field=models.IntegerField(default=0),
        ),
    ]
