# Generated by Django 2.2.6 on 2019-11-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191114_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ROH', 'ROH'), ('AEW', 'AEW'), ('WWE', 'WWE'), ('NJPW', 'NJPW'), ('IMPACT WRESTLING', 'Impact Wrestling')], max_length=50, verbose_name='Company')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.Category')),
            ],
            options={
                'verbose_name_plural': 'company',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
